LHASocialWork/Areas/Admin/Models/Accounts/AccountsModel.cs
using System.ComponentModel;
using LHASocialWork.Core.MVCContrib;

namespace LHASocialWork.Areas.Admin.Models.Accounts
{
    public class AccountsModel : GridModel<AccountModel> { }

    public class AccountModel
    {
        [DisplayName("Email Address")]
        public virtual string Email { get; set; }
        [DisplayName("First Name")]
        public virtual string FirstName { get; set; }
        [DisplayName("Last Name")]
        public virtual string LastName { get; set; }
        [DisplayName("Phone Number")]
        public virtual long PhoneNumber { get; set; }
    }
}

LHASocialWork/Models/Account/AccountLogInModel.cs
namespace LHASocialWork.Models.Account
{
    public class AccountLogInModel
    {
        public string EmailAddress { get; set;}
        public string Password { get; set; }
        public bool RememberMe { get; set; }
        public string ReturnUrl { get; set; }
    }
}

LHASocialWork/Models/Account/AccountSearchByNameModel.cs
using System.Collections.Generic;
using LHASocialWork.Models.Shared;

namespace LHASocialWork.Models.Account
{
    public class AccountSearchByNameModel : SearchModel
    {
        public AccountSearchByNameModel() : base("Name")
        {
            term = "";
        }
    }
}

LHASocialWork/Models/Account/CreateAccountModel.cs
using System.ComponentModel.DataAnnotations;
using LHASocialWork.Models.Templates;

namespace LHASocialWork.Models.Account
{
    public class CreateAccountModel
    {
        [Required]
        public SystemInfo SystemInfo { get; set; }
        [Required]
        public PersonalInfo PersonInfo { get; set; }
        [Required]
        public Address Address { get; set; }
    }
}

LHASocialWork/Models/Account/CreateAccountViewModel.cs
using LHASocialWork.Models.Templates;

namespace LHASocialWork.Models.Account
{
    public class CreateAccountViewModel : CreateAccountModel
    {
        public CreateAccountViewModel()
        {
            SystemInfo = new SystemInfo();
            PersonInfo = new PersonalInfo();
            Address = new Address();
        }
        public string ReturnUrl { get; set; }
        public string FormPostAction { get; set; }
    }
}

LHASocialWork/Models/Account/RegisterModel.cs
using System.ComponentModel.DataAnnotations;
using LHASocialWork.Validation.Attributes;

namespace LHASocialWork.Models.Account
{
    [PropertiesMustMatch("Password", "ConfirmPassword", ErrorMessage = "The password and confirmation password do not match.")]
    public class RegisterModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email address")]
        public string Email { get; set; }

        [Required]
        [ValidatePasswordLength]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        public string ConfirmPassword { get; set; }
    }
}

LHASocialWork/Areas/Admin/Controllers/AccountsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using LHASocialWork.Areas.Admin.Models.Accounts;
using LHASocialWork.Controllers;
using LHASocialWork.Entities;
using LHASocialWork.Models.Account;
using LHASocialWork.Models.Shared;
using LHASocialWork.Repositories.Criteria;
using MvcContrib.Pagination;

namespace LHASocialWork.Areas.Admin.Controllers
{
    public class AccountsController : AdminBaseController
    {
        public AccountsController(BaseServiceCollection baseServiceCollection) : base(baseServiceCollection)
        {
        }

        #region Index

        public ActionResult Index(GridOptionsModel options)
        {
            options.Column = options.Column == "id" ? options.Column = "Email" : options.Column;

            var userSearchCriteria = new UsersSearchCriteria
                                         {
                                             Ascending = options.Ascending,
                                             OrderByProperty = options.Column,
                                         };

            var users = AccountService.FindUsers(userSearchCriteria);
            var usersModel = new AccountsModel
                                 {
                                     Data = Mapper.Map<IEnumerable<User>, IEnumerable<AccountModel>>(users).AsPagination(options.Page, 10),
                                     Options = options
                                 };
            return View(usersModel);
        }

        #endregion

        #region Create Account

        public ActionResult Create()
        {
            return View(new CreateAccountViewModel { FormPostAction = "Create" });
        }

        [HttpPost]
        public ActionResult Create(CreateAccountModel model)
        {
            if (ModelState.IsValid)
            {
                var user = Mapper.Map<CreateAccountModel, User>(model);
                if (!AccountService.SaveUser(user).InvalidValues.Any())
                {
                    DisplayMessage("User Created Successfully");
                    return RedirectToAction("Index");
                }
                AddValidationResults(user.InvalidValues);
            }
            var viewModel = Mapper.Map<CreateAccountModel, CreateAccountViewModel>(model);
            viewModel.FormPostAction = "Create";
            return View(viewModel);
        }

        #endregion
    }
}

LHASocialWork/Controllers/AccountsController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.Security;
using AutoMapper;
using LHASocialWork.Core.Filters;
using LHASocialWork.Entities;
using LHASocialWork.Models.Account;
using LHASocialWork.Models.Shared.JSON;
using LHASocialWork.Repositories.Criteria;
using LHASocialWork.Services.Account;
using LHASocialWork.Services.Authentication;

namespace LHASocialWork.Controllers
{
    [RequireHttps]
    public class AccountsController : BaseController
    {
        public AccountsController (BaseServiceCollection baseServiceCollection) : base(baseServiceCollection){}

        #region Index

        [RequiresAuthentication]
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        #endregion

        #region Register

        [RequireHttps, RequiresAnonymous()]
        public ActionResult Register(string returnUrl)
        {
            return View(new CreateAccountViewModel { FormPostAction = "Register", ReturnUrl = returnUrl });
        }

        [RequireHttps, HttpPost, ValidateAntiForgeryToken, RequiresAnonymous()]
        public ActionResult Register(CreateAccountModel model)
        {
            if (ModelState.IsValid)
            {
                var user = Mapper.Map<CreateAccountModel, User>(model);
                user = AccountService.SaveUser(user);
                if (!user.InvalidValues.Any())
                {
                    if (Request["returnUrl"] != null)
                        return Redirect(Request["returnUrl"]);
                    return RedirectToAction("Index", "Home");
                }
                AddValidationResults(user.InvalidValues);
                DisplayError("Registration failed.  There are " + user.InvalidValues.Length + " error(s) on the page.");
            }

            var invalidViewModel = Mapper.Map<CreateAccountModel, CreateAccountViewModel>(model);
            return View(invalidViewModel);
        }

        #endregion

        #region Authentication

        [RequireHttps]
        public ActionResult LogIn(string returnUrl)
        {
            if (User != null)
                return RedirectToAction("Index", "Home");

            return View(new AccountLogInModel { ReturnUrl = returnUrl });
        }

        [HttpPost, ValidateAntiForgeryToken, RequireHttps]
        public ActionResult LogIn(AccountLogInModel model)
        {
            if (User == null)
            {
                if (!ModelState.IsValid)
                    return View(model);
                if (!AuthenticationService.ValidateUser(model.EmailAddress, HashString(model.Password)))
                {
                    DisplayError("Sorry, invalid username and/or password.  Please try again.");
                    return View(model);
                }
                SetAuthCookie(model);
                if (!string.IsNullOrEmpty(model.ReturnUrl))
                    return Redirect(model.ReturnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        private void SetAuthCookie(AccountLogInModel model)
        {
            var ticket = GetFormsAuthenticationTicket(model.EmailAddress, model.RememberMe);
            var encryptedTicket = FormsAuthentication.Encrypt(ticket);
            var authCookie = new HttpCookie(
                                        FormsAuthentication.FormsCookieName,
                                        encryptedTicket) { Secure = true };
            Response.SetCookie(authCookie);
        }

        [RequiresAuthentication, RequireHttps]
        public ActionResult LogOut()
        {
            if (User != null)
                FormsAuthentication.SignOut();
            if (Request["returnUrl"] != null)
                return Redirect(Request["returnUrl"]);
            return RedirectToAction("Index", "Home");
        }

        private static FormsAuthenticationTicket GetFormsAuthenticationTicket(string userName, bool isPersistent)
        {
            return new FormsAuthenticationTicket(1,
                    userName,
                    DateTime.Now,
                    DateTime.Now.AddMinutes(60),
                    isPersistent,
                    String.Empty,
                    FormsAuthentication.FormsCookiePath);
        }

        private static string HashString(string unhashedString)
        {
            return FormsAuthentication.HashPasswordForStoringInConfigFile(unhashedString, FormsAuthPasswordFormat.SHA1.ToString());
        }


        #endregion

        #region Search

        [RequiresAuthentication, HttpGet]
        public ActionResult SearchByName(AccountSearchByNameModel searchModel)
        {
            var search = new UsersSearchCriteria
                             {
                                 NameIsLike = searchModel.term,
                                 DistinctRootEntity = true,
                                 OrderByProperty = "FirstName",
                             };
            var users = AccountService.FindUsers(search);
            if (Request.IsAjaxRequest())
                return Json(users.Select(x => new JQueryAutoCompleteResponseModel(x.Id.ToString(), string.Format("{0} {1}", x.FirstName, x.LastName))),
                        JsonRequestBehavior.AllowGet);
            return RedirectToAction("Index", "Home");
        }

        #endregion
    }
}

LHASocialWork/Views/Accounts/ChangePassword.cshtml
@inherits System.Web.Mvc.WebViewPage<LHASocialWork.Models.ChangePasswordModel>

@{
    View.Title = "Change Password";
    LayoutPage = "~/Views/Shared/_Layout.cshtml";
}

<h2>Change Password</h2>
<p>
    Use the form below to change your password. 
</p>
<p>
    New passwords are required to be a minimum of @View.PasswordLength characters in length.
</p>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true, "Password change was unsuccessful. Please correct the errors and try again.")
    <div>
        <fieldset>
            <legend>Account Information</legend>

            <div class="editor-label">
                @Html.LabelFor(m => m.OldPassword)
            </div>
            <div class="editor-field">
                @Html.PasswordFor(m => m.OldPassword)
                @Html.ValidationMessageFor(m => m.OldPassword)
            </div>

            <div class="editor-label">
                @Html.LabelFor(m => m.NewPassword)
            </div>
            <div class="editor-field">
                @Html.PasswordFor(m => m.NewPassword)
                @Html.ValidationMessageFor(m => m.NewPassword)
            </div>

            <div class="editor-label">
                @Html.LabelFor(m => m.ConfirmPassword)
            </div>
            <div class="editor-field">
                @Html.PasswordFor(m => m.ConfirmPassword)
                @Html.ValidationMessageFor(m => m.ConfirmPassword)
            </div>

            <p>
                <input type="submit" value="Change Password" />
            </p>
        </fieldset>
    </div>
}

LHASocialWork/Views/Accounts/ChangePasswordSuccess.cshtml
@inherits System.Web.Mvc.WebViewPage

@{
    View.Title = "Change Password";
    LayoutPage = "~/Views/Shared/_Layout.cshtml";
}

<h2>Change Password</h2>
<p>
    Your password has been changed successfully.
</p>

LHASocialWork/Views/Accounts/CreateAccountPartial.cshtml
@inherits System.Web.Mvc.WebViewPage<LHASocialWork.Models.Account.CreateAccountViewModel>

@using System.Web.Mvc.Html
@using System.Web.Mvc

@{Html.EnableClientValidation();}
@using (Html.BeginForm(Model.FormPostAction ?? "Register", "Accounts", FormMethod.Post, new { @class = "formContainer tabbedFormValidation" }))
{       
    @Html.AntiForgeryToken();
    @Html.HiddenFor(x => x.ReturnUrl);
	<h2 style='text-align:center;'>Create Account</h2>
                      
    <div id="tabs">
        <ul>            
            <li><a href="#fragment-1"><span>Account</span></a></li>
            <li><a href="#fragment-2"><span>Name</span></a></li>
            <li><a href="#fragment-3"><span>Address</span></a></li>
        </ul>
        <div id="fragment-1">
            @Html.Editor("SystemInfo")
        </div>
        <div id="fragment-2">
            @Html.EditorFor(m => m.PersonInfo)            
        </div>
        <div id="fragment-3">
            @Html.EditorFor(m => m.Address)            
        </div>
    </div>
    
    <div class='submitButtonContainer' style='padding-left:216px;'>
       <div class='button'>
            @Html.ActionLink("Cancel", "Index")
       </div>
       <div class='button'>
            <input type="submit" value="Register" />
       </div>       
    </div>
}


<script type="text/javascript" src="@Url.Content("~/Scripts/jQuery.UI/jquery-ui-1.8.6.custom.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jQuery.Custom/LHA.FormValidation.js")"></script>
<script type="text/javascript">
    $(function () {
        $("#tabs").tabs();
    });
</script>


LHASocialWork/Views/Accounts/LogIn.cshtml
@inherits System.Web.Mvc.WebViewPage<LHASocialWork.Models.Account.AccountLogInModel>
@using System.Web.Mvc.Html
@using System.Web.Mvc

@{
    View.Title = "LogIn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{Html.RenderPartial("LogInPartial", Model);}

LHASocialWork/Views/Accounts/LogInPartial.cshtml
@inherits System.Web.Mvc.WebViewPage<LHASocialWork.Models.Account.AccountLogInModel>
@using System.Web.Mvc.Html
@using System.Web.Mvc


@using (Html.BeginForm("LogIn", "Accounts", FormMethod.Post, new { @class = "smallFormContainer" })) {
@Html.AntiForgeryToken();
<h2>Log On</h2>
<p>
    Please enter your username and password. @Html.ActionLink("Register", "Register", new { returnUrl = Model.ReturnUrl }) if you don't have an account.
</p>
    @Html.HiddenFor(x => x.ReturnUrl);
    <div>
        <div class="editor-label">
            @Html.LabelFor(m => m.EmailAddress)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.EmailAddress)
            @Html.ValidationMessageFor(m => m.EmailAddress)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.Password)
        </div>
        <div class="editor-field">
            @Html.PasswordFor(m => m.Password)
            @Html.ValidationMessageFor(m => m.Password)
        </div>

        <div class="editor-label">
            @Html.CheckBoxFor(m => m.RememberMe)
            @Html.LabelFor(m => m.RememberMe)
        </div>

        <p>
            <input id="submit" type="submit" value="Log On" class='button' style='height:23px;' />
        </p>
    </div>
}

LHASocialWork/Views/Accounts/Register.cshtml
@inherits System.Web.Mvc.WebViewPage<LHASocialWork.Models.Account.CreateAccountViewModel>

@using System.Web.Mvc.Html
@using System.Web.Mvc

@{
    View.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{Html.RenderPartial("CreateAccountPartial", Model);}